2026.07.01

전처리

In [1]:
# 반정형 데이터 -> 정형 데이터로
import re
import csv
import pandas as pd

In [9]:
# path
log_file_path = 'sample_logs.log' 
output_csv_path = 'parsed_logs.csv'

In [10]:
log_pattern = re.compile(
r'(?P<ip>\d+\.\d+\.\d+\.\d+)\s'           # IP 주소
r'- - \[(?P<datetime>[^\]]+)\] '          # 날짜 및 시간
r'"(?P<method>GET|POST|PUT|DELETE|HEAD) ' # HTTP 메서드
r'(?P<path>[^ ]+).*?"\s'                  # 요청 경로
r'(?P<status>\d{3})\s'                    # 상태 코드
r'(?P<size>\d+)'                          # 응답 크기
)

In [17]:
# 파싱된결과 저장 리스트
parsed_logs = []
# 로그 파일 읽기 및 정규식적용
with open(log_file_path, 'r') as f:
    for line in f:
        match = log_pattern.search(line)
        if match:
            parsed_logs.append(match.groupdict()) #

In [18]:
print(parsed_logs)

[]

In [19]:
# CSV로 저장
with open(output_csv_path, 'w', newline='') as csvfile:
    fieldnames = ['ip', 'datetime', 'method', 'path', 'status', 'size']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    for entry in parsed_logs:
        writer.writerow(entry)
print("보안 로그가CSV로 저장되었습니다:", output_csv_path)

보안 로그가CSV로 저장되었습니다: parsed_logs.csv

In [20]:
import re
import pandas as pd
# 로그 파일 경로
log_file_path = 'sample_logs.log'
# 정규 표현식패턴 정의
log_pattern = re.compile(
    r'(?P<ip>\d+\.\d+\.\d+\.\d+)\s'
    r'- - \[(?P<datetime>[^\]]+)\] '
    r'"(?P<method>GET|POST|PUT|DELETE) '
    r'(?P<path>[^ ]+).*?" '
    r'(?P<status>\d{3}) '
    r'(?P<size>\d+)'
)

In [21]:
# 결과 저장
log_entries = []
with open(log_file_path, 'r') as f:
    for line in f:
        match = log_pattern.search(line)
        if match:
            entry = match.groupdict()
            # datetime을 datetime 객체로변환
            entry['datetime'] = pd.to_datetime(entry['datetime'], format='%d/%b/%Y:%H:%M:%S %z')
            entry['status'] = int(entry['status'])
            entry['size'] = int(entry['size'])
            log_entries.append(entry)
# DataFrame 생성
df = pd.DataFrame(log_entries)
# 결과 확인
print(df.head())

Empty DataFrame
Columns: []
Index: []

In [29]:
import pandas as pd
# 데이터프레임생성
data = {'Name': ['Alice', 'Bob', None],
        'Age': [25, None, 30],
        'Score': [85, 90, None]}
df = pd.DataFrame(data)
# 결측치가있는 행 제거
df_no_missing_rows = df.dropna()
print(df_no_missing_rows)
print('*'* 50)
# 결측치가있는 열 제거
df_no_missing_cols = df.dropna(axis=1)
print(df_no_missing_cols)

    Name   Age  Score
0  Alice  25.0   85.0
**************************************************
Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [30]:
# 데이터프레임생성
data = {'Name': ['Alice', 'Bob', None],
        'Age': [25, None, 30],
        'Score': [85, 90, None]}
df = pd.DataFrame(data)
# 평균으로대체
df['Age'] = df['Age'].fillna(df['Age'].mean())
# 중간값으로대체
df['Score'] = df['Score'].fillna(df['Score'].median())
# 최빈값으로대체
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])
print(df)

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  27.5   90.0
2  Alice  30.0   87.5

In [25]:
import numpy as np

In [44]:
# 이상치 처리
data = {'score': [70, 75, 80, 85, 90, 150]}
df = pd.DataFrame(data)

In [45]:
Q1 = df['score'].quantile(0.25) # 1사분위수
Q3 = df['score'].quantile(0.75) # 3사분위수
IQR = Q3 - Q1
print(Q1, Q3, IQR)

76.25 88.75 12.5

In [46]:
low_ = Q1 - 1.5 * IQR
up_ = Q3 + 1.5 * IQR
print('up', up_)
print('low', low_)

up 107.5
low 57.5

In [47]:
df_result = df[ (df['score']<low_) | (df['score']>up_)]
df_result

   score
5    150

In [49]:
df_result1 = df[ (df['score']>=low_) & (df['score']<=up_)]
df_result1

   score
0     70
1     75
2     80
3     85
4     90

In [51]:
df['score'] = df['score'].astype(float)
df.loc[df['score']<low_, 'score'] = low_
df.loc[df['score']>up_, 'score'] = up_

In [52]:
df

   score
0   70.0
1   75.0
2   80.0
3   85.0
4   90.0
5  107.5

In [63]:
# 중복 데이터 처리
import pandas as pd
# 예제 데이터
data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
        'Age': [25, 30, 25, 35, 30],
        'Score': [85, 90, 85, 95, 90]}
df = pd.DataFrame(data)
print('원본 데이터프레임:')
print(df)

원본 데이터프레임:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [ ]:
print(df.duplicated())
print(df.duplicated().sum())
print(df.duplicated(subset=['Name']).sum())

0    False
1    False
2     True
3    False
4     True
dtype: bool
2
2
0    False
1    False
2     True
3    False
4     True
dtype: bool

In [59]:
df_cleared = df.drop_duplicates()
df_cleared

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
3  Charlie   35     95

In [61]:
df_cleared1 = df.drop_duplicates(keep='last')
df_cleared1

      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [62]:
df_cleared2 = df.drop_duplicates(keep='last', subset=['Name'])
df_cleared2

      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [64]:
df_cleared3 = df.drop_duplicates(keep=False)
df_cleared3

      Name  Age  Score
3  Charlie   35     95

In [58]:
# 전체 중복 행 제거 (모든 열 값이 동일한경우)
df_no_duplicates = df.drop_duplicates(keep='first') # 기본값은keep='first': 첫 번째 중복은남기고나머지는제거
print('1. 중복 데이터제거 후:')
print(df_no_duplicates)
print('*' * 50)
# 특정 열('Name') 기준으로중복 행 제거
df_no_duplicates_by_name = df.drop_duplicates(subset=['Name']) # 이름이같은 경우, 첫 번째만남기고제거
print('2. 이름 기준으로중복 데이터제거 후:')
print(df_no_duplicates_by_name)
print('*' * 50)
# 특정 열('Name') 기준 중복 제거 + 마지막항목을남기고이전 항목 제거
df_no_duplicates_by_name_last = df.drop_duplicates(subset=['Name'], keep='last') # 마지막중복 항목을유지
print('3. 이름 기준으로중복 데이터제거 후, 마지막항목 유지:')
print(df_no_duplicates_by_name_last)
print('*' * 50)
# 특정 열('Name') 기준으로완전한중복 제거 (중복된모든 항목 삭제)
df_no_duplicates_by_name_all = df.drop_duplicates(subset=['Name'], keep=False) # 중복된항목 전부 제거
print('4. 이름 기준으로중복 데이터제거 후, 모든 중복 항목 제거:')
print(df_no_duplicates_by_name_all)

1. 중복 데이터제거 후:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
3  Charlie   35     95
**************************************************
2. 이름 기준으로중복 데이터제거 후:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
3  Charlie   35     95
**************************************************
3. 이름 기준으로중복 데이터제거 후, 마지막항목 유지:
      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90
**************************************************
4. 이름 기준으로중복 데이터제거 후, 모든 중복 항목 제거:
      Name  Age  Score
3  Charlie   35     95

In [65]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\ez\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.5.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached scipy-1.18.0-cp312-cp312-win_amd64.whl (36.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [66]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

In [67]:
data = pd.DataFrame({'Original': [50, 80, 90, 100, 60]})

In [68]:
# 표준화
scaler1 = StandardScaler()
data['scaled_1'] = scaler1.fit_transform(data[['Original']])

# 정규화
scaler2 = MinMaxScaler()
data['scaled_2'] = scaler2.fit_transform(data[['Original']])

data

   Original  scaled_1  scaled_2
0        50 -1.401826       0.0
1        80  0.215666       0.6
2        90  0.754829       0.8
3       100  1.293993       1.0
4        60 -0.862662       0.2

In [69]:
data = pd.DataFrame({'Fruits': ['사과', '배', '포도', '사과', '포도']})

In [70]:
encoder1 = LabelEncoder()
data['Label Encoding'] = encoder1.fit_transform(data['Fruits'])
data

  Fruits  Label Encoding
0     사과               1
1      배               0
2     포도               2
3     사과               1
4     포도               2

In [74]:
one_hot_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = one_hot_encoder.fit_transform(data[['Label Encoding']])

In [75]:
one_hot_columns = one_hot_encoder.get_feature_names_out()
one_hot_df = pd.DataFrame(one_hot_encoded, columns=one_hot_columns)

In [76]:
result_df = pd.concat([data, one_hot_df], axis=1)
result_df

  Fruits  Label Encoding  Label Encoding_0  Label Encoding_1  Label Encoding_2
0     사과               1               0.0               1.0               0.0
1      배               0               1.0               0.0               0.0
2     포도               2               0.0               0.0               1.0
3     사과               1               0.0               1.0               0.0
4     포도               2               0.0               0.0               1.0